### ISSUE TITLE
commit 5-1

### ISSUE THREAD

**Issue by NaderIkladious** [DiscoverMeteor/Microscope#175]
I get this list of errors and i cant do anything else and the only way to make it works again is to undo this step and "mrt remove iron-router" and "meteor remove iron-router" 

`Uncaught TypeError: undefined is not a function dynamic_template.js:371
Uncaught TypeError: Cannot read property 'prototype' of undefined helpers.js:140
Uncaught TypeError: undefined is not a function router.js:61
Uncaught TypeError: Cannot read property 'RouteController' of undefined global-imports.js?784bc180a149e4c10dff977a7f114df67d9952c6:3
Uncaught ReferenceError: Template is not defined template.layout.js?a661fe5e45ce239653a65a819a9d0f6d65b37dca:2
Uncaught ReferenceError: Template is not defined template.post_item.js?117ff25e45e84135568b431c39e8464515e2568c:2
Uncaught ReferenceError: Template is not defined template.posts_list.js?c76dc4345182d4f8cdf992ec6a3f871ddd7166df:2
Uncaught ReferenceError: Router is not defined router.js?66d9427c57526d5f237e08b82b6a7024e16c9743:1
Uncaught ReferenceError: Template is not defined post_item.js?53ea8992b1c61db7e7af3d8a1a46cc4950d6392b:1
Uncaught ReferenceError: Template is not defined posts_list.js?3ac39470eda3cad166ece566024945ce99a4828e:1
Uncaught ReferenceError: Meteor is not defined posts.js?84fb658b3c7edf2ab31caa27648e302502c71325:1
Uncaught ReferenceError: Meteor is not defined main.js?0828a50a027eb25fabd37fccb730e99cc80c48c5:1
Exception in defer callback: TypeError: Cannot read property 'insert' of undefined
    at Utils.extend.autoRender (http://localhost:3000/packages/iron-router.js?af9f4791b8af4582a37d93bcade1eed163a976a8:1636:17)
    at http://localhost:3000/packages/iron-router.js?af9f4791b8af4582a37d93bcade1eed163a976a8:1465:16
    at _.extend.withValue (http://localhost:3000/packages/meteor.js?61916b1060b33931a21f104fbffb67c2f3d493c5:945:17)
    at http://localhost:3000/packages/meteor.js?61916b1060b33931a21f104fbffb67c2f3d493c5:430:45
    at Object.<anonymous> (http://localhost:3000/packages/meteor.js?61916b1060b33931a21f104fbffb67c2f3d493c5:973:22)
    at onGlobalMessage (http://localhost:3000/packages/meteor.js?61916b1060b33931a21f104fbffb67c2f3d493c5:367:23) debug.js:41`

**Comment by skewpar** [comment]
Thanks, was wondering why it wasn't working
