### ISSUE TITLE
Commit 7-7 URL issue

### ISSUE THREAD

**Issue by sherwinan** [DiscoverMeteor/Microscope#187]
On Commit 7-7 where we check for duplicates, if posting successfully the URL of the submission is posted as the URL in the client's browser, not what was in the URL field. For example on the localhost server, if I make a new post with URL yahoo.com, the URL in the submission will be "localhost" no matter what. This also happens on your own 7-7 Instance.

**Comment by codeHatcher** [comment]
@SachaG that was the problem for me. Thanks.
