### ISSUE TITLE
Voting (Commit 13) - Load more does not work

### ISSUE THREAD

**Issue by kvetoslavnovak** [DiscoverMeteor/Microscope#192]
After user has voted "Load more" button for paging disapears.

**Comment by homocreatives** [comment]
When I loaded the instance, I even didn't see the buttons only placeholders.
![screenshot_2](https://cloud.githubusercontent.com/assets/10290941/5603617/1b18e44a-93b0-11e4-8c7a-3077fd424e05.png)

**Comment by tmeasday** [comment]
Hi @kvetoslavnovak - I'm not seeing this problem. Which exact commit of the book were you up to?

**Comment by kvetoslavnovak** [comment]
13-1
http://meteor-book-chapter13-1.meteor.com
https://github.com/DiscoverMeteor/Microscope/commit/chapter13-1

**Comment by tmeasday** [comment]
Hi @kvetoslavnovak - I'm not seeing the problem you describe on that server?
