### ISSUE TITLE
In the Submit Post screen, where does "Message" box come from? (9-2, 9-3)

### ISSUE THREAD

**Issue by alexkchan** [DiscoverMeteor/Microscope#195]
I've been following along, just wondering where the Message box comes from. I looked at the code on Git for 'submit_post.html' and I don't see where the Message box would be.. but it shows up on the live instance .. ? 

I'm really new to web dev in general, background in C and Java.

**Comment by tmeasday** [comment]
Hey @alexkchan - do you mean the `alert()`? It's a kind of weird built-in browser thing from the very very old days that `alert()` exists and fires up a little message box. It's useful at times though.

https://developer.mozilla.org/en-US/docs/Web/API/Window.alert
