### ISSUE TITLE
spin package

### ISSUE THREAD

**Issue by victorbstan** [DiscoverMeteor/Microscope#198]
The current (meteor 1+) convention to add packages is to use `meteor add ...` instead of `mrt`, in light of this change, trying to add the `spin` package is not possible. What are workarounds? 

```
meteor add spin
 => Errors while parsing arguments:

While adding package spin:
error: no such package
```

**Comment by SachaG** [comment]
It should be `meteor add sacha:spin`. What version of the book are you using? If it's not the online version, when did you download it?

**Comment by victorbstan** [comment]
OK I'll try that, I couldn't find it on atmosphere when I tried searching for spin...
