### ISSUE TITLE
13.5 Advanced Publications Sidebar: Publish function incorrectEDIT:Sorry, my fault

### ISSUE THREAD

**Issue by vazamb** [DiscoverMeteor/Microscope#199]
Hey,

love your book but I found a bug (maybe depreciated syntax?) in chapter 13.5
This:

Meteor.publish('posts', function(options) {
  return Posts.find({}, options);
});

should be

Meteor.publish('posts', function(options) {
  return Posts.find(options);
});

EDIT: I am sorry, it was me being stupid. However, I think it would be useful for beginners to note that they should use the above syntax when they are passing search  queries and not options to the publish function.

**Comment by tmeasday** [comment]
Thanks @vazamb :)
