### ISSUE TITLE
Small error in animation chapter: animate class not mentioned.

### ISSUE THREAD

**Issue by MichaelOber** [DiscoverMeteor/Microscope#202]
In the animation chapter, the style.css excerpt shows the class as

    .post{
        position:relative;
        transition:all 300ms 0ms ease-in;
    } 

When the source code actually has the transition in a post.animate class:

    .post.animate{
        -webkit-transition: all 300ms 0ms;
        -moz-transition: all 300ms 0ms ease-in;
        -o-transition: all 300ms 0ms ease-in;
        transition: all 300ms 0ms ease-in; }

I think this is worth noting in the chapter because the animation logic that follows adds and removes this animation class, and the class isn't mentioned until then. This is something that might be obvious to most (especially those that have used the animate.css library), but I think it's best to include to clear up any possible confusion.

GREAT job on the book and new chapter.

**Comment by tmeasday** [comment]
Thanks @MichaelOber - I think you are right that we should call it out and it sounds like there's a mistake there.

**Comment by tmeasday** [comment]
This is really a problem with the book so I'll move this issue there.
