### ISSUE TITLE
Sanitized and reported to the client as: Match failed [400]

### ISSUE THREAD

**Issue by GiraffeSlacks** [DiscoverMeteor/Microscope#204]
In the Pagination chapter there is the following code:

```JavaScript
Meteor.publish('posts', function(options) {
  check(options, {
    sort: Object,
    limit: Number
  });
  return Posts.find({}, options);
});
```

The `check()` function creates a Meteor error:

```
I20150216-11:35:38.893(-8)? Exception from sub LMiCJQKiFpnLh6fWu Error: Match error: Expected object, got undefined
I20150216-11:35:38.894(-8)?     at checkSubtree (packages/check/match.js:275:1)
I20150216-11:35:38.894(-8)?     at check (packages/check/match.js:32:1)
I20150216-11:35:38.894(-8)?     at [object Object]._handler (app\server\publications.js:4:5)
I20150216-11:35:38.894(-8)?     at packages/check/match.js:109:1
I20150216-11:35:38.894(-8)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150216-11:35:38.894(-8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1597:1)
I20150216-11:35:38.894(-8)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150216-11:35:38.894(-8)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150216-11:35:38.894(-8)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150216-11:35:38.894(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150216-11:35:38.896(-8)? Sanitized and reported to the client as: Match failed [400]
```

If I use `console.log('options: '+options)` before `check()` I get two executions of this with the first one always resulting in `undefined` (specifically, I get two executions when I refresh the page but when Meteor recompiles I get only one and it is `undefined`.)

I'm not quite well-versed enough with Meteor to know why this is running twice nor why the first time it is undefined. (On the second run i get the expected data `[object Object]`.)

To sum up, this is the output I have with the added `console.log()` statement (see first and last lines.)

```
I20150216-11:52:08.388(-8)? options: undefined
I20150216-11:52:08.389(-8)? Exception from sub XjqT8wyJTvKe6cnTW Error: Match error: Expected object, got undefined
I20150216-11:52:08.389(-8)?     at checkSubtree (packages/check/match.js:275:1)
I20150216-11:52:08.389(-8)?     at check (packages/check/match.js:32:1)
I20150216-11:52:08.389(-8)?     at [object Object]._handler (app\server\publications.js:5:5)
I20150216-11:52:08.389(-8)?     at packages/check/match.js:109:1
I20150216-11:52:08.389(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150216-11:52:08.389(-8)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150216-11:52:08.389(-8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1597:1)
I20150216-11:52:08.389(-8)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150216-11:52:08.390(-8)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150216-11:52:08.390(-8)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150216-11:52:08.400(-8)? 
I20150216-11:52:08.399(-8)? Sanitized and reported to the client as: Match failed [400]
I20150216-11:52:08.427(-8)? options: [object Object]
```

I won't be surprised if this ends up being a typo somewhere on my part but I've looked over the code several times and can't find any place where I have deviated incorrectly.

**Comment by ashfaqh** [comment]
I am facing the same problem. Any fix for this?

**Comment by GiraffeSlacks** [comment]
I'm at work right now so I can't check this (and haven't worked on this since around the time I opened this) but on the Pagination page search for `return Meteor.subscribe('posts'` and make sure that your code is exactly like what is in the book at every instance where you find a match.

I looked at the code again and in each instance, where the publication is used, the subscription appears to be passing the correct object structure. It's possible that I had deviated from their instructions somehow and didn't notice it.

Also, instead of a plain `console.log()` statement, like I originally wrote above, you can dig into the `options` variable a little more with this: `console.log(JSON.stringify(options))`. That can show you what's in the object rather than just identifying it as `Object`.

**Comment by ashfaqh** [comment]
Thanks for the pointers. I found the problem. I had left the
Meteor.Subscribe('posts') inside Router.configure. This caused the error.
After removing this subscription, it works perfect.

**Comment by tmeasday** [comment]
@GiraffeSlacks - I would say most likely this is your issue also -- you probably missed the fact that you have to remove the older `Meteor.subscribe('posts')` that we added in an earlier chapter.

Let me know if that's not it.

**Comment by GiraffeSlacks** [comment]
@tmeasday That's very possible. I did find it hard to identify code that was removed. The problem with the code is sometimes it's disorienting and not obvious exactly where you're supposed to be (in a file). Also, when code is removed it's just a matter of not being present in the new code (as I recall) rather than explicitly being shown as removed. (I know the code is available on Github. I think there is room for improvement in the book.)

**Comment by tmeasday** [comment]
Hmm, ok makes sense @GiraffeSlacks. Thanks for the feedback.

**Comment by ericmcgregor** [comment]
I'm getting something similar on this same chapter.  so far everything has been flawless... i can't seem to figure out what is going wrong here.  i have literally copied everything directly from the github repo for this chapter.  I'm kind of at a loss here.


        I20150528-09:34:12.733(-5)? Exception from sub posts id QZwdEnztd6oHASbNs Error: Match error: Expected object, got string
        I20150528-09:34:12.733(-5)?     at checkSubtree (packages/check/match.js:275:1)
        I20150528-09:34:12.733(-5)?     at check (packages/check/match.js:32:1)
        I20150528-09:34:12.733(-5)?     at [object Object].Meteor.publish.Comments.find.postId [as _handler] (app/server/publications.js:2:5)
        I20150528-09:34:12.733(-5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
        I20150528-09:34:12.733(-5)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
        I20150528-09:34:12.733(-5)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
        I20150528-09:34:12.734(-5)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
        I20150528-09:34:12.734(-5)?     at packages/ddp/livedata_server.js:546:1
        I20150528-09:34:12.734(-5)? Sanitized and reported to the client as: Match failed [400]
        I20150528-09:34:12.734(-5)?

**Comment by SachaG** [comment]
Maybe add a console.log() before the check() to see what exactly you're passing that's causing the problem?

**Comment by ericmcgregor** [comment]
you know what, it turns out i had not removed the line "Meteor.subscribe('posts', 'bob-smith');" from the main.js file in a previous section.  I must have missed it.

sorry about that.  I guess to GiraffeSlacks point, it can be easy to miss something like that.  Not sure how you'd fix it... overall i find this tutorial really really great.  don't know if maybe at the end of each chapter there could be a terminal command you could run that would just pull down that instance from github and just overwrite your files?  But, honestly, it's really solid.
