### ISSUE TITLE
.container-fluid inside .container

### ISSUE THREAD

**Issue by hamoid** [DiscoverMeteor/Microscope#205]
If I understand right http://getbootstrap.com/css/, there should be no nested .container or .container-fluid in the document. But the layout.html declares a .container, and the header.html a nested .container-fluid. 

Also "Content should be placed within columns, and only columns may be immediate children of rows." Something like: 

    container
      row
        column
        column
      row
        column
        column

Is maybe Microscope not following exactly the Bootstrap way? (I'm not sure, still learning). I started a larger project based on Microscope, but it seems I have to change this part.

**Comment by SachaG** [comment]
Looks like you're right, that `.container-fluid` div doesn't seem to be doing anything. We can probably remove it. 

I don't think we use either `.row` or `.column` though.
