### ISSUE TITLE
Routing Chapter:  No Preview

### ISSUE THREAD

**Issue by jmar42** [DiscoverMeteor/Microscope#209]
After I went through the routing chapter, it wouldn't allow me to preview?  I downloaded the router, and entered the new code and no preview no longer.

**Comment by tmeasday** [comment]
Hi @jmar42 - I'm not sure what you mean by preview? Are you seeing some Javascript errors in the browser console?

**Comment by jmar42** [comment]
When I try to view the app in the browser, nothing happens.  No app appears.  Prior to the Router chapter, I was able to view app in the browser.

**Comment by tmeasday** [comment]
But do you see an error in the browser console?

**Comment by jmar42** [comment]
It says:  Uncaught Error:  No such template spinner

**Comment by tmeasday** [comment]
Looks like you forgot to add the spin package?

**Comment by jmar42** [comment]
Yes thanks! But it still doesn't load right around 5.1 and on.  Some of the
code changes on the way down make it say "Loading".  That's it. And no page
load.

**Comment by jmar42** [comment]
I figured it out, I had a style sheet in wrong folder.  Thx for above help :D

**Comment by brianlmerritt** [comment]
Just in case anyone else blunders here:
    `meteor add sacha:spin`

**Comment by rockzc** [comment]
thanks, it works
