### ISSUE TITLE
Header markup does not match deployed instance

### ISSUE THREAD

**Issue by athyuttamre** [DiscoverMeteor/Microscope#210]
I noticed that the HTML used for the `header` in `main.html` does not match the one in the deployed instance [here](http://meteor-book-chapter3-1.meteor.com). This of course creates different appearances for the two, with only the deployed version matching the screenshot in the book.

In `main.html`, the markup is:

```html
<header class="navbar navbar-default" role="navigation"> 
  <div class="navbar-header">
    <a class="navbar-brand" href="/">Microscope</a>
  </div>
</header>
```

In the deployed instance, the markup is:

```html
<header class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/">Microscope</a>
   </div>
</header>
```

**Comment by tmeasday** [comment]
Hi @athyuttamre - I think the deployed instance (and screenshot) is just a little out of date and still using bootstrap2. I'll make sure we overwrite it when we do the next release of the book.
