### ISSUE TITLE
Comments do not delete when post is removed

### ISSUE THREAD

**Issue by sangyoo91** [DiscoverMeteor/Microscope#211]
What code snippet should I add to delete comments with corresponding postId?

I've tried to write my own but have failed...

**Comment by tmeasday** [comment]
Hey @sangyoo91,

I think the idea approach is to write a `postDelete` method which handles the job of deleting the post and any associated data (i.e. comments in this case).

Something like:

```
Meteor.methods({
   postDelete: function(id) {
      Posts.remove(id);
      Comments.remove({postId: id}, {multi: true});
   }
});
