### ISSUE TITLE
Questions in Publications and Subscriptions

### ISSUE THREAD

**Issue by Denly** [DiscoverMeteor/Microscope#214]
Hi, I have 2 questions in this chapter https://book.discovermeteor.com/chapter/publications-and-subscriptions
1. why sometimes return Posts.find({'author':'Tom'}) and some return Posts.find({ author :'Tom'})? The 'author' and author are different.
2. Why return Posts.find({}, {fields: {date: false}}); needs the blank {} ??
Thank you

**Comment by edipotrebol** [comment]
Hi @Denly 
I can reply to the second questions. The reason why the code use blank {} is to indicate there is no *where clause* into the query. You do not need to use it every time. Just in case that you want to fill second parameter on the find() function.
I hope it helps.

**Comment by Denly** [comment]
Thank you!!! It helps! @edipotrebol

**Comment by edipotrebol** [comment]
@Denly you welcome!

**Comment by tmeasday** [comment]
Hi @Denly - re: your first question:

In javascript, object keys can be specified with or without quotes. So

```
{a: 'b'} === {'a': 'b'}
```

You do need to use the quotes in certain cases, for instance: `{'foo-bar': 'baz'}`.

**Comment by Denly** [comment]
Thank your kind response so much!  I never noticed this rule before...
