### ISSUE TITLE
Chapter 7 - HTML accidentally used in JS code

### ISSUE THREAD

**Issue by CaptSaltyJack** [DiscoverMeteor/Microscope#215]
Right above the 7-2 commit.

    <span class="line">Posts = new Mongo.Collection('posts');</span><span class="line">
    </span><span class="line highlighted added">Posts.allow({</span><span class="line highlighted added">  insert: function(userId, doc) {</span><span class="line highlighted added">    // only allow posting if you are logged in</span><span class="line highlighted added">    return !! userId;</span><span class="line highlighted added">  }</span><span class="line highlighted added">});</span><span class="line">
    </span>

**Comment by tmeasday** [comment]
Hi @CaptSaltyJack - thanks for reporting this. I'm not quite sure what you are saying though -- is this in the web site? Are you seeing those spans?

**Comment by CaptSaltyJack** [comment]
Sorry, forgot to come back and post that the issue is fixed. Either it was a weird glitch or someone fixed it. :)

**Comment by tmeasday** [comment]
Ahh, ok thanks!
