### ISSUE TITLE
Does somebody know how to modify "Microscope" code for using as a Meteor package?

### ISSUE THREAD

**Issue by edipotrebol** [DiscoverMeteor/Microscope#218]
This code runs well as application but when I want to integrate into another big app as a package generating a package.js in its root folder, nothing works as I expected.

Please, can somebody help me?

**Comment by tmeasday** [comment]
Hi @edipotrebol I'm not sure this is possible. There's a lot of code in microscope that assumes it's a application. I think it'd be difficult to make it a package. You'd probably be better off forking microscope and extending it to do what you want to do if you want to build on it's functionality.

**Comment by edipotrebol** [comment]
Thanks @tmeasday. That's what I did. If I get something I will inform you.
