### ISSUE TITLE
lib/router.js is missing line endings, hard to read

### ISSUE THREAD

**Issue by rolfedh** [DiscoverMeteor/Microscope#220]
The line endings seem to be missing from lib/router.js. The text displays poorly in the chapter on routing, making it harder to read and understand.

**Comment by tmeasday** [comment]
Hi @rolfedh - which format are you reading it in? It looks ok to me (on the website in Safari).

**Comment by rolfedh** [comment]
Hi Tom,

I was looking at it using Chrome on Windows 8. I'll follow up with some
screenshots...

Rolfe

**Comment by rolfedh** [comment]
It looks fine now. I think you can close this issue.

**Comment by tmeasday** [comment]
Thanks @rolfedh
