### ISSUE TITLE
Spinner keeps spinning

### ISSUE THREAD

**Issue by amitda** [DiscoverMeteor/Microscope#225]
Hello,

After adding the following code the spinner keeps on spinning. Please help.

Amit
![screen shot 2015-04-19 at 5 00 35 pm](https://cloud.githubusercontent.com/assets/589523/7221925/ae9044fe-e6b5-11e4-980e-175f22f9bef6.png)

![screen shot 2015-04-19 at 4 56 11 pm](https://cloud.githubusercontent.com/assets/589523/7221916/4e6dab2a-e6b5-11e4-807b-95201bc42ed5.png)

**Comment by amitda** [comment]
I was able to resolve the issue. I am closing this.

**Comment by githubmann** [comment]
i like the theme.can you tell me the name
