### ISSUE TITLE
question about onRendered vs rendered: chapter 9.5

### ISSUE THREAD

**Issue by charue808** [DiscoverMeteor/Microscope#236]
I was curious is there a difference when creating the errors package in the original helpers/errors.js file Template.errors.onRendered is used and then in the package code /errors_list.js  Template.meteorErrors.rendered is used. 

I couldn't find anything in the meteor documentation regarding "rendered" but read on stackoverflow that from version 1.04 rendered has been renamed to onRendered. 

Sorry trying to figure out what the difference is, it seems like they both work but that onRendered is the preferred name going forward.

**Comment by dpatte** [comment]
rendered was the old way, and onRendered() is the new way; but I have found that some packages expect rendered and some expect onRendered(). For me at least, they are not interchangeable, despite what others may say.

**Comment by charue808** [comment]
okay cool, thanks.. Do you think expectation is due to what meteor version is being used? So if it's Meteor 0.9 then  .rendered is expected, but if that package was written after 1.04 then .onRendered.

Thanks just trying to wrap my brain around it.
