### ISSUE TITLE
Commit 10-3

### ISSUE THREAD

**Issue by ganchan** [DiscoverMeteor/Microscope#243]
Meteor.call('comment', comment, function(error, commentId) {
      if (error){
        throwError(error.reason);
      } else {
        $body.val('');
      }
    });
should be
    Meteor.call('comment', comment, function(error, result) {
      if (error){
        Errors.throw(error.reason);
      } else {
        $body.val('');
      }
    });

**Comment by SachaG** [comment]
I don't really see why? Closing this for now.
