### ISSUE TITLE
Chapter 8 - Problem with Edit/Delete posts

### ISSUE THREAD

**Issue by fbid** [DiscoverMeteor/Microscope#254]
Hi there, I have a problem with editing and deleting posts from the edit page.

To be more specific: 
- the submit button, when clicked, reloads the form fields with the original post values.
- the delete button does nothing. It doesn't even show the confirm() window.

I suppose it could be something wrong with permissions, but I can't figure out what.

**Comment by SachaG** [comment]
Did you manage to work this out?

**Comment by EdwardYZN** [comment]
I have the exact same problem...
@SachaG, could you please help me out?
