### ISSUE TITLE
Microscope project error message: your application is crushing 

### ISSUE THREAD

**Issue by mahfuzkhalili** [DiscoverMeteor/Microscope#259]
I am following through the Discover Meteor microscope project, after page 44 get the following message in the browser:
" 
C:\Users\Mahfuz\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
ReferenceError: Router is not defined
    at github_microscope/lib/router.js:1:1
    at C:\microscope\.meteor\local\build\programs\server\app\github_microscope\lib\router.js:106:4
    at C:\microscope\.meteor\local\build\programs\server\boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Mahfuz\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    at C:\microscope\.meteor\local\build\programs\server\boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
"

**Comment by SachaG** [comment]
Sounds like you didn't add Iron Router?

**Comment by mahfuzkhalili** [comment]
In the Document page 73, it is showing to add iron router but I am still at
page 44

**Comment by SachaG** [comment]
If you're before Iron Router is added, then you should not have `Router` in your code?

**Comment by mahfuzkhalili** [comment]
It was referring to the router in the git-hub.  I guess after creating github-microscope folder and running git command line utilities in the document it is referring to that folder.  

After adding iron router the error is now different " C:\Users\Mahfuz\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
Error: A method named '/posts/insert' is already defined
    at livedata_server.js:1536:15
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object]._.extend.methods (livedata_server.js:1532:7)
    at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:923:1)
    at new Mongo.Collection (packages/mongo/collection.js:214:1)
    at lib/collections/posts.js:4:9
    at C:\microscope\.meteor\local\build\programs\server\app\lib\collections\posts.js:14:4
    at C:\microscope\.meteor\local\build\programs\server\boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Mahfuz\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by SachaG** [comment]
It sounds like there are other problems with your codebase. I would recommend either cloning the project again from GitHub, or else making sure you're following the book step by step.

**Comment by mahfuzkhalili** [comment]
I think somehow the steps related to github - document pages 38-40 has created problem in the app directory:
<img width="301" alt="microscope" src="https://cloud.githubusercontent.com/assets/11528745/10238583/ab630f9e-688f-11e5-9d87-41c46fb5e9d0.PNG">

**Comment by SachaG** [comment]
In that case I would suggest either getting more familiar with Git so you can fix the problem, or else just starting over with a fresh repo :)

**Comment by mahfuzkhalili** [comment]
I have checked again files in the documents and steps for cloning in the document page 38 there was no error during the cloning.  There may be conflict in files in the original microscope folder and git_microscope folder. 

<img width="293" alt="microscope" src="https://cloud.githubusercontent.com/assets/11528745/10238701/9467e916-6891-11e5-950a-9df95a233788.PNG">
