### ISSUE TITLE
Checks

### ISSUE THREAD

**Issue by Vitiell0** [DiscoverMeteor/Microscope#262]
I had to manually add the "check" package to get the security check to work in on the postInsert function in section 7.6.

I used "meteor add audit-argument-checks" but was still getting the error that check was undefined. 

Once I used "meteor add check" the postInsert function started working.

**Comment by kkmkoudijs** [comment]
Same here.

**Comment by aleebaba** [comment]
Same here!!
When I submit a post with a url that already exits MongoDB, I got the  error: 
I20151015-22:08:08.715(8)? Exception while invoking method 'postInsert' Referenc
eError: check is not defined
I20151015-22:08:08.718(8)?     at [object Object].Meteor.methods.postInsert (lib
/collections/posts.js:5:5)
I20151015-22:08:08.718(8)?     at packages/check/match.js:109:1
I20151015-22:08:08.718(8)?     at [object Object]._.extend.withValue (packages/m
eteor/dynamics_nodejs.js:56:1)
I20151015-22:08:08.719(8)?     at Object.Match._failIfArgumentsAreNotAllChecked
(packages/check/match.js:108:1)
I20151015-22:08:08.719(8)?     at maybeAuditArgumentChecks (livedata_server.js:1
689:18)
I20151015-22:08:08.719(8)?     at [object Object]._.extend.withValue (packages/m
eteor/dynamics_nodejs.js:56:1)
I20151015-22:08:08.720(8)?     at livedata_server.js:706:40
I20151015-22:08:08.719(8)?     at livedata_server.js:708:19
I20151015-22:08:08.720(8)?     at [object Object]._.extend.withValue (packages/m
eteor/dynamics_nodejs.js:56:1)
I20151015-22:08:08.720(8)?     at livedata_server.js:704:46

**Comment by Oxyrus** [comment]
I added the package and now the posts are saved, however after click on submit I am not redirected to the post, it stays on the submit template, any idea?

**Comment by SachaG** [comment]
We fixed this, thanks :)
