### ISSUE TITLE
9.5 Errors - UI is not defined 

### ISSUE THREAD

**Issue by Vitiell0** [DiscoverMeteor/Microscope#263]
I had to add -  api.use("templating", "client");   - to the Package.onTest function to get the template test to pass

**Comment by oelerpearler** [comment]
Had the same problem and just wanted to confirm/extend this issue:

Error#1: package.js :: line21 :: Had also to use 'templating' in the Package.onTest function, e.g.:
```javascript
api.use(['tinytest', 'test-helpers', 'templating'], 'client');
```
Error#2: errorr_tests.js :: line15 :: Had to replace the 'Template.insert(Template.render( ...' line with:
```javascript
UI.insert(UI.render(Template.meteorErrors), document.body);
```

**Comment by SachaG** [comment]
Thanks, we'll fix this.
