### ISSUE TITLE
localhost:3000 is empty

### ISSUE THREAD

**Issue by asoong-94** [DiscoverMeteor/Microscope#270]
ive been following the coding examples, and running my microscope app. however my localhost:3000 is returning just a blank page? anyone have this issue?

**Comment by siquick** [comment]
Also having this issue...

Seems to be related to this:

`<div class="container">
    <header class="navbar navbar-default" role="navigation"> 
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Microscope</a>
      </div>
    </header>
    <div id="main">
      {{> postsList}}
    </div>
  </div>`

**Comment by yinzSE** [comment]
are you code meteor at terminal ？
and did it console server is running ？
or you can point port with `-p 8080`
