### ISSUE TITLE
Chapter 7-1

### ISSUE THREAD

**Issue by Yonben** [DiscoverMeteor/Microscope#271]
The submit form shouldn't have the 'page' class as it put the form in absolute position and put it on top of the header.

**Comment by Yonben** [comment]
Turned out it's the same with post pages (didn't notice before :/ )

**Comment by SachaG** [comment]
I'm not 100% sure why we're using position:absolute here, it might have to do with how we animate elements. In any case it doesn't really impact the layout so I'll probably leave it as it is.
