### ISSUE TITLE
Chapter 9.5 `Template` should be `Blaze`

### ISSUE THREAD

**Issue by robmoggach** [DiscoverMeteor/Microscope#272]
In the errors chapter the Tinytest code should actually be:

    Blaze.insert(Blaze.render(Template.meteorErrors), document.body);

instead of

    Template.insert(Template.render(Template.meteorErrors), document.body);

not sure if you're updating to current release...

**Comment by paniwani** [comment]
This worked for me as well but I also had to add api.use("templating", "client"); to the Package.onTest function in package.js as mentioned in another Github issue.

**Comment by SachaG** [comment]
Thanks, we'll fix this.
