### ISSUE TITLE
17-1 Intercom Integration

### ISSUE THREAD

**Issue by Guilliatt** [DiscoverMeteor/Microscope#276]
Following the book tutorial verbatim, Intercom won't recognise your app. The fix for this that worked for me, is to ensure that the config file in main.js is not the same as the dummy data in Discover Meteor, but is lifted from the new config file given by Intercom themselves, i.e.

  window.intercomSettings = {
    app_id: "tbwxmttl",
    name: "Jane Doe", // Full name
    email: "customer@example.com", // Email address
    created_at: 1312182000 // Signup date as a Unix timestamp
  };

A simple fix, but one that I hope helps someone!

**Comment by SachaG** [comment]
I'm not sure why using different dummy data would make it work. I'll have to look into this, thanks.
