### ISSUE TITLE
Issue post Notifications chapter

### ISSUE THREAD

**Issue by tomthebuzz** [DiscoverMeteor/Microscope#279]
After I complete the Notifcations chapter the Meteor webserver throws the
following error and and the app doesn't show any notifications in the dropdown.

(webapp_server.js:419) Error serving static file Error: Forbidden

It does allow to add comments without any issues. 

Have tried the following without any success:

1) Tripple checked the code changes (against the book and github)
2) Restarted the server and reset the app

Any hints - seems to be a more generic issue and not (just) related to the code?
Thx
-Tom

**Comment by SachaG** [comment]
Sorry, I haven't been able to reproduce this error. Closing it for now.
