### ISSUE TITLE
chapitre 7.6 en francais

### ISSUE THREAD

**Issue by scenaristeur** [DiscoverMeteor/Microscope#280]
bjr, il manque la ligne d'install du package 'meteor add audit-argument-checks'
et il semblerait que cela ne soit pas suffisant --> message d'erreur : Reference Error:check is not defined
résolu par meteor add check

**Comment by SachaG** [comment]
Voir ici pour le repo Discover Meteor en français: https://github.com/DiscoverMeteor/DiscoverMeteor_fr
