### ISSUE TITLE
1.3 fails

### ISSUE THREAD

**Issue by interfaith** [DiscoverMeteor/Microscope#281]
the latest version does upgrade to 1.3

**Comment by SachaG** [comment]
Working on this :)

**Comment by interfaith** [comment]
Hi,

I got your book. Is there any discussion about porting jquery plugins to
meteor ?
Dealing with module.exports for example.

Cheers,
Mark

On Tue, May 17, 2016 at 6:30 PM, Sacha Greif <notifications@github.com>
wrote:

> Closed #281 <https://github.com/DiscoverMeteor/Microscope/issues/281>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DiscoverMeteor/Microscope/issues/281#event-663815705>
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
