### ISSUE TITLE
add bootstrap-dropdown & accounts password fail

### ISSUE THREAD

**Issue by ccbcqbz** [DiscoverMeteor/Microscope#84]
In chapter 6 "Adding User", examples are given:

> mrt add accounts-ui-bootstrap-dropdown
>   --> error: no such package: 'spark'
> mrt add accounts-password
>   --> error: Package named accounts-password doesn't exist in your meteor installation, smart.json, or on atmosphere

Both are failed with the error above on my machine. 
meteorite version: 0.7.2 
meteor version: 0.8.0

**Comment by 3210jr** [comment]
Ran into this problem with meteor 1x. Just incase anyone else is. 
for the accounts-password run : meteor add accounts-password
